### PR TITLE
added sky box with level reset on player collision

### PR DESCRIPTION
**Pull request by thespicyboy**

### CODE REVIEW

**Comment by danpprince** [comment]
Is there a new script file or changes to an existing one that implements the level resetting?

**Comment by thespicyboy** [comment]
I think it's using scripts I added in earlier PRs. Should be a scene object addition, sky box prefab, and a new tag

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by danpprince** [comment]
I think it would be best to call this something besides "sky box", which is Unity's terminology for the background graphics in a scene: https://docs.unity3d.com/2019.2/Documentation/Manual/class-Skybox.html

Maybe "LevelBounds" or something?

We have also refactored master to separate scenes into prefabs to avoid future merge conflicts. We'll need to get that integrated here, which could cause some annoying conflicts that will hopefully be prevented in the future.

**Comment by PatrickDolanJ** [comment]
Out of Bounds Boxes Needed, also Goal Prefeb .prefab file is broken? There may be other problems from merging also.

**Comment by danpprince** [comment]
Closing this PR in favor of one that I added more changes to: https://github.com/danpprince/katamari-golf/pull/39/files

**Pull request closed without merging**
